apiVersion: app.interviews.myrepo.io/v1alpha1
kind: MyAppResource
metadata:
  labels:
    app.kubernetes.io/name: myappresource
    app.kubernetes.io/instance: myappresource-sample
    app.kubernetes.io/part-of: angi
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: angi
  name: myappresource-sample
spec:
  # TODO(user): Add fields here
